version: '3'
services: 
    web:
        build: .
        command: >
            bash -c "cd ./data_collection
            && python manage.py runserver 0.0.0.0:8000"
        ports: 
            - 8000:8000